[package]
name = "hello-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
ferris-says = "0.3.1"

[[bin]]
name = "box"
path = "src/box/main.rs"


[[bin]]
name = "linked_list"
path = "src/linked_list/main.rs"